### ISSUE TITLE
základní funkčnost

### ISSUE THREAD

**Issue by Keeehi** [nextras/orm-demo-nette#1]
Dokud nebude dokumentace k orm, šlo by toto upravit tak, aby se to dalo po stáhnutí hned použít?

config.local.example.neon -> config.local.neon

No a pak už dostávám hlášku

```
Nette\DI\ServiceCreationException

Service 'orm.mappers.comments': Service of type Nette\Database\Context needed by Nextras\Orm\Mapper\Nette\NetteMapper::__construct() not found. Did you register it in configuration file?
```

**Comment by hrach** [comment]
Je to kvuli nekompatibilite nette/databse, ktera se nedavno zmenila. Staci upravit config. Srr, jeste jsem to nezvladl udelat, zvlaste proto,z e orm bude mit novej backend nextras/dbal.

**Comment by Keeehi** [comment]
ok, a byl by nějaký rychlonávod, jak orm rozchodit abych si ho mohl vyzkoušet? Snažím se to zprovoznit z db-benchmark z kterého jsem si to vykopíroval. 

```
{
    "require": {
        "php": "~5.4",
        "nette/nette": "@dev",
        "nextras/orm": "@dev"
    },
    "minimum-stability": "dev"
}
```

```
nette:
    database:
        dsn: 'mysql:host=127.0.0.1;dbname=orm'
        options:
            lazy: yes
extensions:
    orm: Nextras\Orm\Bridge\NetteDI\OrmExtension
orm:
    model: OrmDemo\Orm
```

Při této konfiguraci dostávám

```
Nette\DI\ServiceCreationException

Service of type OrmDemo\Orm used in @var annotation at Property [ <default> public $orm ] not found. Did you register it in configuration file?
```

Normálně bych čekal, že OrmDemo\Orm mi jako službu zaregistruje ta extension. Ať se to ale snažím upravovat jak chci, pořád se mi to nedaří.
